### ISSUE TITLE
Missing Credits 

### ISSUE THREAD

**Issue by ading2210** [titodelas/edpuzzle-script#1]
Hi,

I'm the original creator of [ading2210/edpuzzle-answers](https://github.com/ading2210/edpuzzle-answers), which is licensed under the GNU GPLv3. This repository seems to just be a [link to my code](https://github.com/titodelas/edpuzzle-script/blob/main/edpuzzle_bookmark.js). I know this probably isn't a legal requirement, but could you at least credit me somewhere in the readme? It's not very nice to link to someone else's work and claim it as your own. Also it looks like you changed the license to MIT, which violates the GPL.

Thanks,
ading2210

**Comment by titodelas** [comment]
Hi,
I'm sorry to listen to that. I used to have this account shared, so probably my teammate have it skid your project. And I didn't log in since August. I'm going to change the license and give you credits, also I will talk to him to fix the problem. Thank you to make the issue, because like you said is not nice to have skidded project in my GitHub.

I hope you the best wishes in your next project.
titodelas
